/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutPitchShifterRouteImport } from './routes/_layout/pitch-shifter'
import { Route as LayoutKeyBpmAnalyzerRouteImport } from './routes/_layout/key-bpm-analyzer'
import { Route as LayoutBpmChangerRouteImport } from './routes/_layout/bpm-changer'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPitchShifterRoute = LayoutPitchShifterRouteImport.update({
  id: '/pitch-shifter',
  path: '/pitch-shifter',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutKeyBpmAnalyzerRoute = LayoutKeyBpmAnalyzerRouteImport.update({
  id: '/key-bpm-analyzer',
  path: '/key-bpm-analyzer',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBpmChangerRoute = LayoutBpmChangerRouteImport.update({
  id: '/bpm-changer',
  path: '/bpm-changer',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/bpm-changer': typeof LayoutBpmChangerRoute
  '/key-bpm-analyzer': typeof LayoutKeyBpmAnalyzerRoute
  '/pitch-shifter': typeof LayoutPitchShifterRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  '/bpm-changer': typeof LayoutBpmChangerRoute
  '/key-bpm-analyzer': typeof LayoutKeyBpmAnalyzerRoute
  '/pitch-shifter': typeof LayoutPitchShifterRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/bpm-changer': typeof LayoutBpmChangerRoute
  '/_layout/key-bpm-analyzer': typeof LayoutKeyBpmAnalyzerRoute
  '/_layout/pitch-shifter': typeof LayoutPitchShifterRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/bpm-changer' | '/key-bpm-analyzer' | '/pitch-shifter' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/bpm-changer' | '/key-bpm-analyzer' | '/pitch-shifter' | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/bpm-changer'
    | '/_layout/key-bpm-analyzer'
    | '/_layout/pitch-shifter'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pitch-shifter': {
      id: '/_layout/pitch-shifter'
      path: '/pitch-shifter'
      fullPath: '/pitch-shifter'
      preLoaderRoute: typeof LayoutPitchShifterRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/key-bpm-analyzer': {
      id: '/_layout/key-bpm-analyzer'
      path: '/key-bpm-analyzer'
      fullPath: '/key-bpm-analyzer'
      preLoaderRoute: typeof LayoutKeyBpmAnalyzerRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/bpm-changer': {
      id: '/_layout/bpm-changer'
      path: '/bpm-changer'
      fullPath: '/bpm-changer'
      preLoaderRoute: typeof LayoutBpmChangerRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutBpmChangerRoute: typeof LayoutBpmChangerRoute
  LayoutKeyBpmAnalyzerRoute: typeof LayoutKeyBpmAnalyzerRoute
  LayoutPitchShifterRoute: typeof LayoutPitchShifterRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutBpmChangerRoute: LayoutBpmChangerRoute,
  LayoutKeyBpmAnalyzerRoute: LayoutKeyBpmAnalyzerRoute,
  LayoutPitchShifterRoute: LayoutPitchShifterRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
